language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8"
  - "3.9-dev"

env:
  global:
    - POETRY_VIRTUALENVS_CREATE=false

stages:
  - quality_check

before_install:
  - pip install poetry

install:
  - poetry install -v

script:
  pytest .

jobs:
  include:
    - stage: quality_check
      script:
        - pre-commit run --all-files

deploy:
  provider: script
  script: poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
  skip_cleanup: true
  on:
    tags: true
